export const Colors = {
  burgundy: '#6B1A2A',
  burgundyLight: '#A0283F',
  gold: '#C9973A',
  goldLight: '#E8BC6A',
  cream: '#F5EDD6',
  dark: '#1A0A00',
  darkBrown: '#2D1A0A',
  brown: '#5C3317',
  warmGray: '#8C7B6B',
  lightGray: '#E8DDD0',
  white: '#FAFAF8',
  success: '#4A7C59',
  warning: '#C9973A',
  error: '#C0392B',
  info: '#2980B9',
  mapMarkerCave: '#6B1A2A',
  mapMarkerCommerce: '#C9973A',
  mapMarkerUser: '#2980B9',
};

export const API = {
  BASE_URL: 'https://overpass-api.de/api/interpreter',
  CENTER: {
    latitude: 47.3220,
    longitude: 5.0415,
  },
  DATASETS: {
    COMMERCES: 'commerces-de-dijon',
    EQUIPEMENTS_PUBLICS: 'equipements-publics',
    EQUIPEMENTS_ADMIN: 'equipements-administratifs',
    EQUIPEMENTS_SOCIAUX: 'equipements-sociaux',
    BATIMENTS: 'batis_ampliweb@dijon-metropole',
  },
  DEFAULT_RADIUS: 5000,
  MAX_RECORDS: 100,
};

export const COMMERCE_CATEGORIES = {
  CAVE: ['cave', 'vins', 'caviste', 'vin'],
  RESTAURANT: ['restaurant', 'brasserie', 'bistrot', 'café', 'bar'],
  GASTRONOMIE: ['fromagerie', 'charcuterie', 'épicerie', 'traiteur', 'boulangerie'],
  ARTISANAT: ['artisan', 'poterie', 'galerie'],
};

export const MOCK_CAVES = [
  {
    id: 'mock-1',
    name: 'Caves de la Reine Pédauque',
    address: '2 route de Beaune, Aloxe-Corton',
    latitude: 47.0654,
    longitude: 4.8699,
    category: 'cave' as const,
    description: 'Cave historique au cœur de la Côte de Beaune.',
    phone: '+33 3 80 25 00 00',
    website: 'https://www.reine-pedauque.com',
    openingHours: 'Lun-Dim: 10h-18h',
    appellations: ['Aloxe-Corton', 'Corton-Charlemagne'],
    distance: null,
    source: 'mock' as const,
  },
  {
    id: 'mock-2',
    name: 'Bouchard Père & Fils',
    address: '15 Château de Beaune, Beaune',
    latitude: 47.0248,
    longitude: 4.8393,
    category: 'cave' as const,
    description: 'Domaine emblématique de Bourgogne.',
    phone: '+33 3 80 24 80 24',
    website: 'https://www.bouchard-pereetfils.com',
    openingHours: 'Lun-Dim: 9h30-18h30',
    appellations: ['Beaune', 'Meursault'],
    distance: null,
    source: 'mock' as const,
  },
  {
    id: 'mock-3',
    name: 'Le Pré aux Clercs',
    address: '13 place de la Libération, Dijon',
    latitude: 47.3228,
    longitude: 5.0412,
    category: 'restaurant' as const,
    description: 'Restaurant gastronomique face au Palais des Ducs.',
    phone: '+33 3 80 38 05 05',
    website: 'https://www.lepreauclercs.com',
    openingHours: 'Mar-Sam: 12h-14h, 19h-22h',
    appellations: [],
    distance: null,
    source: 'mock' as const,
  },
  {
    id: 'mock-4',
    name: 'Moutarde Fallot',
    address: '31 rue de la Chouette, Beaune',
    latitude: 47.0231,
    longitude: 4.8401,
    category: 'commerce' as const,
    description: 'Moutarderie artisanale fondée en 1840.',
    phone: '+33 3 80 22 10 02',
    website: 'https://www.fallot.com',
    openingHours: 'Lun-Sam: 9h30-12h30, 14h-19h',
    appellations: [],
    distance: null,
    source: 'mock' as const,
  },
  {
    id: 'mock-5',
    name: 'Cave Millésime — Dijon Centre',
    address: '15 rue de la Liberté, Dijon',
    latitude: 47.3219,
    longitude: 5.0407,
    category: 'cave' as const,
    description: 'Caviste indépendant au cœur de Dijon.',
    phone: '+33 3 80 30 15 45',
    website: null,
    openingHours: 'Mar-Sam: 10h-19h30',
    appellations: ['Gevrey-Chambertin', 'Meursault'],
    distance: null,
    source: 'mock' as const,
  },
  {
    id: 'mock-6',
    name: 'Brasserie Zeste',
    address: '5 rue Amiral Roussin, Dijon',
    latitude: 47.3215,
    longitude: 5.0398,
    category: 'restaurant' as const,
    description: 'Brasserie moderne avec sélection de vins locaux.',
    phone: '+33 3 80 67 14 32',
    website: null,
    openingHours: 'Lun-Dim: 12h-23h',
    appellations: [],
    distance: null,
    source: 'mock' as const,
  },
];

export const ROUTES_VIN = [
  {
    id: 'route-1',
    name: 'Route des Grands Crus',
    description: 'De Dijon à Santenay — 60 km à travers les appellations les plus prestigieuses de Bourgogne.',
    duration: '1 journée',
    distance: '60 km',
    difficulty: 'Facile' as const,
    waypoints: [
      { name: 'Dijon', lat: 47.3220, lng: 5.0415 },
      { name: 'Marsannay-la-Côte', lat: 47.2716, lng: 5.0048 },
      { name: 'Gevrey-Chambertin', lat: 47.2244, lng: 4.9714 },
      { name: 'Vougeot', lat: 47.1722, lng: 4.9546 },
      { name: 'Nuits-Saint-Georges', lat: 47.1192, lng: 4.9504 },
      { name: 'Beaune', lat: 47.0248, lng: 4.8393 },
    ],
    color: '#6B1A2A',
  },
  {
    id: 'route-2',
    name: 'Route des Hautes-Côtes',
    description: 'Les villages perchés au-dessus de la Côte de Nuits. Vins d\'altitude et paysages spectaculaires.',
    duration: 'Demi-journée',
    distance: '35 km',
    difficulty: 'Modéré' as const,
    waypoints: [
      { name: 'Nuits-Saint-Georges', lat: 47.1192, lng: 4.9504 },
      { name: 'Villars-Fontaine', lat: 47.1600, lng: 4.8900 },
      { name: 'Meuilley', lat: 47.1800, lng: 4.8750 },
    ],
    color: '#C9973A',
  },
];